// 15 Comprehensive Certified Showroom Cars Data for Shri Rani Cars (ஸ்ரீ ராணி கார்ஸ்)
window.INITIAL_CARS = [
  {
    id: 'car_101',
    title: 'BMW 5 Series 530d M Sport',
    brand: 'BMW',
    model: '5 Series 530d',
    variant: '530d M Sport 3.0L Inline-6',
    year: 2019,
    price: 3250000,
    original_price: 3450000,
    kms: 72000,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    body_type: 'Sedan',
    color: 'Carbon Black Metallic',
    owners: '1st Owner',
    insurance: 'Comprehensive Valid till Dec 2026',
    rto: 'TN 30 (Salem)',
    mileage: '17.4 kmpl',
    engine: '2993 cc (6-Cylinder Turbo)',
    power: '265 bhp / 620 Nm',
    status: 'Available',
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      'Adaptive M Suspension',
      'Harman Kardon Surround Sound',
      'BMW Gesture Control & Display Key',
      'Wireless Apple CarPlay & Android Auto',
      'Soft-Close Luxury Doors',
      'Electric Glass Sunroof',
      '4-Zone Climate Control',
      '360-Degree Surround Camera'
    ],
    description: 'Immaculately maintained BMW 530d M Sport in Carbon Black. Powered by the legendary 3.0L straight-six diesel engine producing 620 Nm torque. Single owner, company maintained with complete service records in Salem.'
  },
  {
    id: 'car_102',
    title: 'Hyundai Creta SX (O) Turbo DCT',
    brand: 'Hyundai',
    model: 'Creta SX(O)',
    variant: 'SX (O) 1.5 Turbo GDi 7DCT',
    year: 2021,
    price: 1475000,
    original_price: 1550000,
    kms: 48000,
    fuel_type: 'Petrol',
    transmission: 'Manual',
    body_type: 'SUV',
    color: 'Polar White',
    owners: '1st Owner',
    insurance: 'Valid till Nov 2026',
    rto: 'TN 54 (Salem)',
    mileage: '16.8 kmpl',
    engine: '1497 cc Petrol',
    power: '138 bhp',
    status: 'Available',
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      'Voice-Enabled Panoramic Sunroof',
      '10.25-inch Touchscreen Navigation',
      'Bose 8-Speaker Audio System',
      'Front Ventilated Seats',
      'Electronic Parking Brake with Auto Hold',
      'Air Purifier with AQI Display',
      'Trio Beam LED Headlamps'
    ],
    description: 'Top-spec Hyundai Creta SX(O) in pristine Polar White. Flawless body, zero accidental history, premium leatherette upholstery, verified kilometers with single owner credentials.'
  },
  {
    id: 'car_103',
    title: 'Toyota Fortuner 2.8 4x4 AT',
    brand: 'Toyota',
    model: 'Fortuner 4x4',
    variant: '2.8 4x4 Automatic Diesel',
    year: 2020,
    price: 3690000,
    original_price: 3850000,
    kms: 90000,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    body_type: 'SUV',
    color: 'Phantom Black',
    owners: '1st Owner',
    insurance: 'Comprehensive Valid till Oct 2026',
    rto: 'TN 27 (Salem)',
    mileage: '14.2 kmpl',
    engine: '2755 cc D-4D Diesel',
    power: '201 bhp / 500 Nm',
    status: 'Available',
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      '4x4 High/Low Electronic Drive Selector',
      'Downhill Assist Control (DAC)',
      '18-inch Chamfered Alloy Wheels',
      '8-Way Powered Driver & Co-Driver Seats',
      '11-Speaker JBL Audio System',
      'Dual Zone Automatic Climate Control',
      '7 SRS Airbags'
    ],
    description: 'The undisputed king of Indian roads! Toyota Fortuner 4x4 Automatic in Phantom Black. Bulletproof Toyota reliability, meticulously maintained, 100% non-accidental assurance.'
  },
  {
    id: 'car_104',
    title: 'Hyundai Verna SX (O) 1.5 Turbo',
    brand: 'Hyundai',
    model: 'Verna SX',
    variant: 'SX (O) 1.5 Turbo MT',
    year: 2022,
    price: 1245000,
    original_price: 1320000,
    kms: 28000,
    fuel_type: 'Petrol',
    transmission: 'Manual',
    body_type: 'Sedan',
    color: 'Fiery Red',
    owners: '1st Owner',
    insurance: 'Valid till Sep 2026',
    rto: 'TN 54 (Salem)',
    mileage: '18.6 kmpl',
    engine: '1497 cc VTVT Petrol',
    power: '115 bhp',
    status: 'Available',
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      'Electric Smart Sunroof',
      'Ventilated Front Leather Seats',
      '8-inch Touchscreen with Apple CarPlay',
      'Wireless Phone Charger',
      'Smart Trunk Opening',
      '6 Airbags & ESP',
      'Diamond Cut Alloy Wheels'
    ],
    description: 'Striking Hyundai Verna SX in Fiery Red. Single owner, very low mileage, smooth gearbox, ventilated cooling seats, and exceptional highway comfort.'
  },
  {
    id: 'car_105',
    title: 'Mercedes-Benz C-Class C 220d',
    brand: 'Mercedes',
    model: 'C-Class',
    variant: 'C 220d Progressive Line',
    year: 2020,
    price: 3850000,
    original_price: 4100000,
    kms: 46000,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    body_type: 'Sedan',
    color: 'Obsidian Black Metallic',
    owners: '1st Owner',
    insurance: 'Zero Dep Valid till Nov 2026',
    rto: 'TN 30 (Salem)',
    mileage: '18.9 kmpl',
    engine: '1950 cc OM654 Diesel',
    power: '194 bhp / 400 Nm',
    status: 'Available',
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      'Panoramic Dual Sunroof',
      '64-Color Ambient Mood Lighting',
      'Burmester Premium Surround Sound',
      'Mercedes MBUX Digital Cockpit',
      '9G-TRONIC Automatic Transmission',
      'Active Brake Assist & 7 Airbags'
    ],
    description: 'Supreme luxury Mercedes-Benz C-Class with full panoramic roof and Burmester sound. Driven single-handed, authorized Mercedes-Benz service track, certified non-accidental.'
  },
  {
    id: 'car_106',
    title: 'Audi A4 40 TFSI Technology',
    brand: 'Audi',
    model: 'A4',
    variant: '40 TFSI Technology 2.0L',
    year: 2021,
    price: 3490000,
    original_price: 3700000,
    kms: 38000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'Sedan',
    color: 'Ibis White',
    owners: '1st Owner',
    insurance: 'Comprehensive Valid till Aug 2026',
    rto: 'TN 54 (Salem)',
    mileage: '17.4 kmpl',
    engine: '1984 cc Turbo Petrol',
    power: '190 bhp / 320 Nm',
    status: 'Available',
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      'Audi Virtual Cockpit Plus (Full Digital)',
      'MMI Navigation Plus with Touch Response',
      'Bang & Olufsen 3D Sound System',
      'Matrix LED Headlamps with Dynamic Indicators',
      '3-Zone Deluxe Climate Control',
      'Wireless Phone Charger'
    ],
    description: 'Refined German engineering with Audi Virtual Cockpit and Matrix LEDs. Ultra silent cabin, exhilarating 2.0 TFSI acceleration, spotless showroom condition.'
  },
  {
    id: 'car_107',
    title: 'Mahindra XUV700 AX7 L Diesel AT AWD',
    brand: 'Mahindra',
    model: 'XUV700',
    variant: 'AX7 Luxury Pack Diesel AT AWD',
    year: 2022,
    price: 2180000,
    original_price: 2300000,
    kms: 32000,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    body_type: 'SUV',
    color: 'Midnight Black',
    owners: '1st Owner',
    insurance: 'Zero Dep Valid till Nov 2026',
    rto: 'TN 30 (Salem)',
    mileage: '15.6 kmpl',
    engine: '2198 cc mHawk Diesel',
    power: '182 bhp / 450 Nm',
    status: 'Available',
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      'ADAS Level 2 Autonomous Safety',
      'Skyroof Panoramic Sunroof',
      'Sony 3D 12-Speaker Immersive Audio',
      '360-Degree Surround Camera & Blind Spot Monitor',
      'Dual 10.25-inch High Resolution Screens',
      'Electronic Flush Door Handles'
    ],
    description: 'India’s most advanced SUV with ADAS Level 2 safety and Sony 3D sound. Top-tier AX7 Luxury Pack with All-Wheel Drive, 7-seater comfort, and spotless body.'
  },
  {
    id: 'car_108',
    title: 'Tata Safari Accomplished Plus 6S',
    brand: 'Tata',
    model: 'Safari',
    variant: 'Accomplished+ 6-Seater AT',
    year: 2023,
    price: 2090000,
    original_price: 2240000,
    kms: 21000,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    body_type: 'SUV',
    color: 'Cosmic Gold Metallic',
    owners: '1st Owner',
    insurance: 'Comprehensive Valid till Mar 2027',
    rto: 'TN 54 (Salem)',
    mileage: '16.1 kmpl',
    engine: '1956 cc Kryotec Diesel',
    power: '170 bhp / 350 Nm',
    status: 'Available',
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      'Ventilated 1st & 2nd Row Captain Seats',
      '12.3-inch Cinematic Touchscreen Infotainment',
      'JBL 10-Speaker Audio with Subwoofer',
      'Gesture Controlled Electric Tailgate',
      'Voice-Assisted Panoramic Sunroof with Mood Lighting',
      '7 Airbags & 5-Star BNCAP Safety'
    ],
    description: 'Flagship Tata Safari Accomplished+ with ventilated captain seats in 1st & 2nd row! High-riding presence, 5-Star safety rating, factory warranty valid till 2026.'
  },
  {
    id: 'car_109',
    title: 'Volkswagen Virtus GT Plus 1.5 TSI',
    brand: 'Volkswagen',
    model: 'Virtus GT',
    variant: 'GT Plus 1.5 TSI EVO DSG',
    year: 2022,
    price: 1580000,
    original_price: 1680000,
    kms: 22000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'Sedan',
    color: 'Wild Cherry Red',
    owners: '1st Owner',
    insurance: 'Valid till Sep 2026',
    rto: 'TN 27 (Salem)',
    mileage: '19.4 kmpl',
    engine: '1498 cc 4-Cylinder TSI EVO',
    power: '148 bhp / 250 Nm',
    status: 'Available',
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1619682817481-e994891cd1f5?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1619682817481-e994891cd1f5?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      'Active Cylinder Technology (ACT)',
      'Electric Sunroof',
      '10.1-inch VW Play Touchscreen with Wireless CarPlay',
      'Ventilated Front Seats',
      '8-inch Digital Cockpit',
      '6 Airbags & Electronic Stability Control (ESC)'
    ],
    description: 'German performance sedan! Volkswagen Virtus GT with 1.5 TSI EVO engine and lightning-fast 7-speed DSG gearbox. 5-Star Global NCAP safety, thrilling driving dynamics.'
  },
  {
    id: 'car_110',
    title: 'Toyota Innova Crysta 2.4 VX 7 STR',
    brand: 'Toyota',
    model: 'Innova Crysta',
    variant: '2.4 VX 7-Seater Diesel',
    year: 2021,
    price: 1980000,
    original_price: 2050000,
    kms: 46000,
    fuel_type: 'Diesel',
    transmission: 'Manual',
    body_type: 'MUV',
    color: 'Attitude Black Mica',
    owners: '1st Owner',
    insurance: 'Comprehensive Valid till Mar 2027',
    rto: 'TN 27 (Salem)',
    mileage: '15.6 kmpl',
    engine: '2393 cc (GD Engine)',
    power: '148 bhp',
    status: 'Available',
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      'Captain Seats with Foldable Tray Table',
      'Automatic Climate Control with Rear Vents',
      'Touchscreen with Navigation',
      'Eco & Power Drive Modes',
      '7 SRS Airbags & Hill Assist'
    ],
    description: 'The supreme touring vehicle! VIP single-owner Innova Crysta VX with captain seat arrangement. Legendary Toyota durability, ultra-smooth engine, full service history.'
  },
  {
    id: 'car_111',
    title: 'Mahindra Thar LX Hard Top 4x4',
    brand: 'Mahindra',
    model: 'Thar',
    variant: 'LX 4-Str Hard Top Diesel MT 4WD',
    year: 2023,
    price: 1485000,
    original_price: 1550000,
    kms: 18200,
    fuel_type: 'Diesel',
    transmission: 'Manual',
    body_type: 'SUV',
    color: 'Napoli Black',
    owners: '1st Owner',
    insurance: 'Zero Depreciation Valid till Oct 2026',
    rto: 'TN 30 (Salem)',
    mileage: '15.2 kmpl',
    engine: '2184 cc (mHawk 130)',
    power: '130 bhp',
    status: 'Available',
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      '4x4 Manual Shift-on-Fly with Low Range',
      '18-inch Deep Silver Alloy Wheels',
      '7-inch Touchscreen Infotainment',
      'Roll Cage with ABS & ESP',
      'Tyre Pressure Monitoring (TPMS)'
    ],
    description: 'Iconic lifestyle 4x4 Mahindra Thar in pristine Napoli Black. Fully loaded Hard Top with genuine Mahindra accessories, off-road protection, and low mileage.'
  },
  {
    id: 'car_112',
    title: 'Kia Seltos GTX Plus 1.4 Turbo',
    brand: 'Kia',
    model: 'Seltos',
    variant: 'GTX Plus 1.4 T-GDi 7DCT',
    year: 2022,
    price: 1540000,
    original_price: 1620000,
    kms: 26000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'SUV',
    color: 'Gravity Grey',
    owners: '1st Owner',
    insurance: 'Comprehensive Valid till Nov 2026',
    rto: 'TN 30 (Salem)',
    mileage: '16.5 kmpl',
    engine: '1353 cc Turbo GDi',
    power: '140 bhp',
    status: 'Available',
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      '8-inch Heads-Up Display (HUD)',
      '360-Degree Camera with Blind View Monitor',
      'Bose 8-Speaker Audio System',
      'Front Ventilated Seats',
      'Smart Pure Air Purifier with Perfume Diffuser'
    ],
    description: 'Sporty Kia Seltos GT-Line with Heads-Up Display, Bose sound system, and ventilated seats. Extremely clean interior and exterior with complete service book records.'
  },
  {
    id: 'car_113',
    title: 'Maruti Suzuki Dzire ZXi Plus AMT',
    brand: 'Maruti Suzuki',
    model: 'Dzire',
    variant: 'ZXi Plus AMT (Automatic)',
    year: 2022,
    price: 745000,
    original_price: 790000,
    kms: 28500,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'Sedan',
    color: 'Magma Red',
    owners: '1st Owner',
    insurance: 'Comprehensive Valid till Nov 2026',
    rto: 'TN 54 (Salem)',
    mileage: '22.4 kmpl',
    engine: '1197 cc K-Series DualJet',
    power: '88.5 bhp',
    status: 'Available',
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      'Touchscreen SmartPlay Studio',
      'Cruise Control & Push Button Start',
      'Automatic Climate Control',
      'Reverse Parking Camera & Sensors',
      'Precision Cut Alloy Wheels'
    ],
    description: 'Highest fuel-efficiency sedan in India (22.4 kmpl). Top-end ZXi Plus Automatic with push-button start and reverse camera. Super reliable daily commuter.'
  },
  {
    id: 'car_114',
    title: 'Tata Nexon EV Max XZ+ Lux',
    brand: 'Tata',
    model: 'Nexon EV',
    variant: 'Max XZ+ Lux 40.5 kWh',
    year: 2023,
    price: 1340000,
    original_price: 1420000,
    kms: 16500,
    fuel_type: 'Electric',
    transmission: 'Automatic',
    body_type: 'SUV',
    color: 'Intensi-Teal',
    owners: '1st Owner',
    insurance: 'Zero Dep Valid till Feb 2027',
    rto: 'TN 54 (Salem)',
    mileage: '437 km (Full Charge Range)',
    engine: 'Electric Motor (143 PS)',
    power: '143 PS / 250 Nm',
    status: 'Available',
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      '40.5 kWh High-Density Battery Pack',
      'Fast DC Charging Support',
      'Ventilated Leatherette Front Seats',
      'Wireless Smartphone Charger',
      'Harman Touchscreen Audio'
    ],
    description: 'Zero fuel cost, instantaneous electric torque! India’s #1 Electric SUV in rare Intensi-Teal. Includes home fast charger, battery warranty intact till 2031.'
  },
  {
    id: 'car_115',
    title: 'Honda City ZX 1.5 i-VTEC CVT',
    brand: 'Honda',
    model: 'City',
    variant: 'ZX 1.5 i-VTEC CVT Automatic',
    year: 2020,
    price: 975000,
    original_price: 1040000,
    kms: 41000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'Sedan',
    color: 'Golden Brown Metallic',
    owners: '1st Owner',
    insurance: 'Comprehensive Valid till Jun 2026',
    rto: 'TN 54 (Salem)',
    mileage: '18.4 kmpl',
    engine: '1498 cc i-VTEC',
    power: '119 bhp',
    status: 'Available',
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      'One-Touch Electric Sunroof',
      'Full LED Headlamps 9 Array Inline Shells',
      'LaneWatch Blind Spot Camera System',
      '8-inch Touchscreen with Apple CarPlay',
      '7-Speed Paddle Shift Controls'
    ],
    description: 'The executive benchmark sedan! Honda City ZX top-model with electric sunroof and lane-watch camera. Silky smooth i-VTEC motor with CVT paddle shifts.'
  }
];
