// Initial Rich Inventory Data for Shri Rani Cars (ஸ்ரீ ராணி கார்ஸ்)
window.INITIAL_CARS = [
  {
    id: 'car_101',
    title: 'Maruti Suzuki Dzire ZXi Plus',
    brand: 'Maruti Suzuki',
    model: 'Dzire',
    variant: 'ZXi Plus AMT (Automatic)',
    year: 2022,
    price: 745000,
    original_price: 790000,
    kms: 28500,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'Sedan',
    color: 'Magma Red',
    owners: '1st Owner',
    insurance: 'Comprehensive Valid till Nov 2026',
    rto: 'TN 54 (Salem)',
    mileage: '22.4 kmpl',
    engine: '1197 cc',
    power: '88.5 bhp',
    status: 'Available',
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      'Touchscreen SmartPlay Studio',
      'Android Auto & Apple CarPlay',
      'Cruise Control',
      'Automatic Climate Control',
      'Push Button Start/Stop',
      'Dual Front Airbags',
      'Reverse Parking Camera & Sensors',
      'Precision Cut Alloy Wheels',
      'Electrically Foldable ORVMs'
    ],
    description: 'Immaculately maintained single-owner Maruti Suzuki Dzire ZXi Plus in attractive Magma Red. Complete authorized service history at Salem dealership, brand new Michelin tyres, non-accidental guarantee with full vehicle inspection report.'
  },
  {
    id: 'car_102',
    title: 'Mahindra Thar LX Hard Top 4x4',
    brand: 'Mahindra',
    model: 'Thar',
    variant: 'LX 4-Str Hard Top Diesel MT 4WD',
    year: 2023,
    price: 1485000,
    original_price: 1550000,
    kms: 18200,
    fuel_type: 'Diesel',
    transmission: 'Manual',
    body_type: 'SUV',
    color: 'Napoli Black',
    owners: '1st Owner',
    insurance: 'Zero Depreciation Valid till Oct 2026',
    rto: 'TN 30 (Salem)',
    mileage: '15.2 kmpl',
    engine: '2184 cc (mHawk 130)',
    power: '130 bhp',
    status: 'Available',
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      '4x4 Manual Shift-on-Fly',
      '18-inch Deep Silver Alloy Wheels',
      '7-inch Touchscreen Infotainment',
      'Adventure Statistics Display',
      'Roll Cage with ABS & ESP',
      'Tyre Pressure Monitoring (TPMS)',
      'Roof-mounted Speakers (Drizzle Resistant)',
      'Dual Airbags & ISOFIX Child Mounts'
    ],
    description: 'Iconic lifestyle 4x4 Mahindra Thar in pristine Napoli Black. Fully loaded top-variant Hard Top with genuine Mahindra accessories, off-road underbody protection, and flawless mechanical condition.'
  },
  {
    id: 'car_103',
    title: 'Toyota Innova Crysta 2.4 VX 7 STR',
    brand: 'Toyota',
    model: 'Innova Crysta',
    variant: '2.4 VX 7-Seater Diesel',
    year: 2021,
    price: 1980000,
    original_price: 2050000,
    kms: 46000,
    fuel_type: 'Diesel',
    transmission: 'Manual',
    body_type: 'MUV',
    color: 'Attitude Black Mica',
    owners: '1st Owner',
    insurance: 'Comprehensive Valid till Mar 2027',
    rto: 'TN 27 (Salem)',
    mileage: '15.6 kmpl',
    engine: '2393 cc (GD Engine)',
    power: '148 bhp',
    status: 'Available',
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      'Captain Seats with Ottoman',
      'Automatic Climate Control with Rear AC',
      'Touchscreen with Navigation & Bluetooth',
      'Eco & Power Drive Modes',
      '7 SRS Airbags',
      'Vehicle Stability Control & Hill Start Assist',
      'LED Projector Headlamps & DRLs',
      'Ambient Cabin Illumination'
    ],
    description: 'The king of luxury family touring! VIP single-owner Toyota Innova Crysta VX with captain seat arrangement. Legendary Toyota reliability, super smooth engine, 100% genuine showroom records, perfect for long drives.'
  },
  {
    id: 'car_104',
    title: 'Hyundai Creta SX (O) Turbo DCT',
    brand: 'Hyundai',
    model: 'Creta',
    variant: 'SX (O) 1.4 Turbo Petrol 7DCT',
    year: 2022,
    price: 1590000,
    original_price: 1680000,
    kms: 24000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'SUV',
    color: 'Polar White with Phantom Black Roof',
    owners: '1st Owner',
    insurance: 'Valid till Aug 2026',
    rto: 'TN 54 (Salem West)',
    mileage: '16.8 kmpl',
    engine: '1353 cc Turbo GDi',
    power: '138 bhp',
    status: 'Available',
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      'Panoramic Sunroof (Voice Enabled)',
      '10.25-inch Touchscreen Navigation',
      'Bose Premium 8-Speaker Audio System',
      'Ventilated Front Seats',
      'Paddle Shifters & Drive Modes',
      'Electronic Parking Brake with Auto Hold',
      'Air Purifier with AQI Display',
      'Trio Beam LED Headlamps'
    ],
    description: 'Top-of-the-line Hyundai Creta Turbo DCT with panoramic glass roof and ventilated seats. Extremely smooth dual-clutch transmission, thrilling turbo response, scratchless showroom condition.'
  },
  {
    id: 'car_105',
    title: 'BMW X1 sDrive20d xLine',
    brand: 'BMW',
    model: 'X1',
    variant: 'sDrive20d xLine Steptronic',
    year: 2021,
    price: 2850000,
    original_price: 3100000,
    kms: 34000,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    body_type: 'SUV',
    color: 'Mineral White Metallic',
    owners: '1st Owner',
    insurance: 'Comprehensive Valid till Dec 2026',
    rto: 'TN 30 (Salem)',
    mileage: '19.6 kmpl',
    engine: '1995 cc TwinPower Turbo',
    power: '190 bhp',
    status: 'Available',
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      'Twin-Power Turbo Diesel Engine',
      'Panoramic Glass Sunroof',
      'Dakota Leather Seats with Memory',
      'BMW iDrive with Wireless Apple CarPlay',
      'Ambient Interior Lighting in 6 Colors',
      'Automatic Tailgate with Kick Sensor',
      '8-Speed Steptronic Sport Transmission',
      '18-inch Y-spoke Alloy Wheels'
    ],
    description: 'German luxury at its finest! Doctor owned BMW X1 xLine with panoramic roof and pure leather seating. Unmatched high-speed cruising stability, fuel efficiency up to 20 kmpl, showroom records updated.'
  },
  {
    id: 'car_106',
    title: 'Tata Nexon EV Max XZ+ Lux',
    brand: 'Tata',
    model: 'Nexon EV',
    variant: 'Max XZ+ Lux 40.5 kWh',
    year: 2023,
    price: 1340000,
    original_price: 1420000,
    kms: 16500,
    fuel_type: 'Electric',
    transmission: 'Automatic',
    body_type: 'SUV',
    color: 'Intensi-Teal with White Roof',
    owners: '1st Owner',
    insurance: 'Zero Dep Valid till Feb 2027',
    rto: 'TN 54 (Salem)',
    mileage: '437 km (Full Charge Range)',
    engine: 'Electric Motor (143 PS)',
    power: '143 PS / 250 Nm',
    status: 'Available',
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      '40.5 kWh High-Density Battery Pack',
      'Fast DC Charging Support (0-80% in 56 mins)',
      'Multi-Mode Regenerative Braking',
      'Ventilated Leatherette Front Seats',
      'Wireless Smartphone Charger',
      'Electronic Parking Brake with Auto Hold',
      '7-inch Harman Touchscreen with 8 Speakers',
      'Air Purifier with AQI Display'
    ],
    description: 'Zero fuel cost, maximum torque! India\'s #1 Electric SUV in rare Intensi-Teal dual tone. Includes 7.2 kW home fast charger box, battery and motor warranty intact till 2031 (8 Years / 1,60,000 km).'
  },
  {
    id: 'car_107',
    title: 'MG Hector Sharp 2.0 Diesel',
    brand: 'MG',
    model: 'Hector',
    variant: 'Sharp 2.0 MT Diesel 5-Str',
    year: 2021,
    price: 1320000,
    original_price: 1400000,
    kms: 39000,
    fuel_type: 'Diesel',
    transmission: 'Manual',
    body_type: 'SUV',
    color: 'Starry Black',
    owners: '1st Owner',
    insurance: 'Valid till Sep 2026',
    rto: 'TN 27 (Salem)',
    mileage: '17.4 kmpl',
    engine: '1956 cc Multijet II',
    power: '170 bhp',
    status: 'Available',
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      'Dual Pane Panoramic Sunroof',
      '10.4-inch HD Vertical Touchscreen',
      'Infinity by Harman Sound System with Subwoofer',
      '360-Degree Surround View Camera',
      'Powered 6-Way Driver Seat',
      'Internet Inside with e-SIM Connectivity',
      '6 Airbags, ESP & Traction Control',
      'Electric Tailgate'
    ],
    description: 'Spacious internet-connected SUV with massive panoramic sunroof and 360-degree camera. Powered by refined 2.0L diesel engine, giving effortless highway performance and maximum cabin room.'
  },
  {
    id: 'car_108',
    title: 'Honda City ZX CVT (Sunroof)',
    brand: 'Honda',
    model: 'City',
    variant: 'ZX 1.5 i-VTEC CVT Automatic',
    year: 2020,
    price: 975000,
    original_price: 1040000,
    kms: 41000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'Sedan',
    color: 'Golden Brown Metallic',
    owners: '1st Owner',
    insurance: 'Comprehensive Valid till Jun 2026',
    rto: 'TN 54 (Salem)',
    mileage: '18.4 kmpl',
    engine: '1498 cc i-VTEC',
    power: '119 bhp',
    status: 'Available',
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1619682817481-e994891cd1f5?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1619682817481-e994891cd1f5?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      'One-Touch Electric Sunroof',
      'Full LED Headlamps with 9 Array Inline Shells',
      'LaneWatch Blind Spot Camera System',
      '8-inch Touchscreen with Apple CarPlay & Android Auto',
      'Leather Upholstery with Soft Touch Dashboard',
      '6 Airbags & Vehicle Stability Assist (VSA)',
      '7-Speed Paddle Shift Controls',
      'Diamond Cut R16 Alloy Wheels'
    ],
    description: 'The executive benchmark sedan. Single-owner Honda City ZX top-model with electric sunroof and lane-watch camera. Silky smooth i-VTEC motor with CVT paddle shifts for effortless city and highway driving.'
  },
  {
    id: 'car_109',
    title: 'Kia Seltos GTX Plus 1.4 Turbo',
    brand: 'Kia',
    model: 'Seltos',
    variant: 'GTX Plus 1.4 T-GDi 7DCT',
    year: 2022,
    price: 1540000,
    original_price: 1620000,
    kms: 26000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'SUV',
    color: 'Gravity Grey',
    owners: '1st Owner',
    insurance: 'Comprehensive Valid till Nov 2026',
    rto: 'TN 30 (Salem)',
    mileage: '16.5 kmpl',
    engine: '1353 cc Turbo GDi',
    power: '140 bhp',
    status: 'Available',
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1000&q=80'
    ],
    features: [
      '8-inch Heads-Up Display (HUD)',
      '360-Degree Camera with Blind View Monitor',
      'Bose 8-Speaker Audio System',
      'Front Ventilated Seats',
      'Smart Pure Air Purifier with Perfume Diffuser',
      'Red GT-Line Accent Interior & Exterior',
      'Wireless Phone Charger',
      'Multi-Drive & Traction Control Modes'
    ],
    description: 'Sporty Kia Seltos GT-Line with Heads-Up Display, Bose sound system, and ventilated seats. Extremely clean interior and exterior, driven single-handed with complete Kia Salem service book records.'
  }
];
